import { useState } from 'react'
import type { FormEvent } from 'react'
import './App.css'
import { currency, dealValue, formatDate, monthlyKey, partyName, stages, today, todayDisplay } from './domain'
import type { Deal, DealStage, LedgerType, Party } from './domain'
import { useAppData } from './storage'
import { useCloudData } from './cloud-storage'
import { isSupabaseConfigured, supabase } from './lib/supabase'

type Page = 'Dashboard' | 'Deals' | 'Parties' | 'Offers & Requirements' | 'Transport' | 'Payments' | 'Daily Register' | 'Monthly Ledger' | 'To-Do' | 'Reports'
type ModalType = 'deal' | 'edit-deal' | 'party' | 'payment' | 'edit-payment' | 'trip' | 'offer' | 'requirement' | 'commission' | 'transporter' | 'truck' | 'todo' | null
const nav: Page[] = ['Dashboard', 'Deals', 'Parties', 'Offers & Requirements', 'Transport', 'Payments', 'Daily Register', 'Monthly Ledger', 'To-Do', 'Reports']
const uid = () => crypto.randomUUID()
const dbStage = (stage: DealStage) => stage.toLowerCase().replaceAll(' ', '_')
const dbLedger = (ledger: LedgerType) => ledger.toLowerCase().replaceAll(' ', '_')
const dbTrust = (value: string) => value.toLowerCase()
const paise = (value: number) => Math.round(value * 100)

export default function App() {
  const [localData, setLocalData] = useAppData()
  const [cloudData, setCloudData, cloudLoaded, reloadCloud] = useCloudData()
  const data = isSupabaseConfigured ? cloudData : localData
  const setData = isSupabaseConfigured ? setCloudData : setLocalData
  const [page, setPage] = useState<Page>('Dashboard')
  const [modal, setModal] = useState<ModalType>(null)
  const [returnToDeal, setReturnToDeal] = useState(false)
  const [selectedDealId, setSelectedDealId] = useState<string | null>(null)
  const [selectedPartyId, setSelectedPartyId] = useState<string | null>(null)
  const [editingPaymentId, setEditingPaymentId] = useState<string | null>(null)
  const [dealDraft, setDealDraft] = useState<{ buyerId?: string; sellerId?: string; commodity?: string; quantity?: number; rate?: number; offerId?: string; requirementId?: string } | null>(null)
  const [darkMode, setDarkMode] = useState(() => window.localStorage.getItem('shree-balaje-theme') === 'dark')
  const [notice, setNotice] = useState('')
  const cloudAction = async (action: (ownerId: string) => PromiseLike<{ error: { message: string } | null }>, success: string) => {
    if (!isSupabaseConfigured || !supabase) return false
    const { data: auth, error: authError } = await supabase.auth.getUser()
    if (authError || !auth.user) { setNotice('Your session has ended. Please sign in again.'); return true }
    const result = await action(auth.user.id)
    if (result.error) { setNotice(`Cloud save failed: ${result.error.message}`); return true }
    await reloadCloud()
    setNotice(success)
    return true
  }
  if (isSupabaseConfigured && !cloudLoaded) return <div className="auth-page"><p>Loading cloud business records…</p></div>
  const selectedDeal = data.deals.find((deal) => deal.id === selectedDealId)
  const selectedParty = data.parties.find((party) => party.id === selectedPartyId)
  const editingPayment = data.payments.find((payment) => payment.id === editingPaymentId)
  const name = (id: string) => partyName(data.parties, id)
  const phone = (id: string) => data.parties.find((party) => party.id === id)?.phone || '—'
  const paymentTotal = (id: string, ledger: LedgerType) => data.payments.filter((p) => p.dealId === id && p.ledger === ledger).reduce((sum, p) => sum + p.amount, 0)
  const obligation = (deal: Deal, ledger: LedgerType) => ledger === 'Commodity' ? { amount: dealValue(deal), expectedPayment: deal.expectedPayment } : data.obligations.find((item) => item.dealId === deal.id && item.ledger === ledger)
  const dueFor = (deal: Deal, ledger: LedgerType) => Math.max(0, (obligation(deal, ledger)?.amount ?? 0) - paymentTotal(deal.id, ledger))
  const due = (deal: Deal) => dueFor(deal, 'Commodity')
  const active = data.deals.filter((deal) => !['Closed', 'Cancelled'].includes(deal.stage))
  const overdue = data.deals.filter((deal) => deal.stage !== 'Cancelled' && due(deal) > 0 && deal.expectedPayment < today)
  const updateDeal = async (id: string, changes: Partial<Deal>) => {
    const deal = data.deals.find((item) => item.id === id)
    if (!deal || deal.stage === 'Cancelled') { setNotice('Cancelled Deals keep their history and cannot be changed.'); return }
    if (isSupabaseConfigured && supabase) {
      const patch: Record<string, unknown> = {}
      if (changes.buyerId) patch.buyer_party_id = changes.buyerId
      if (changes.sellerId) patch.seller_party_id = changes.sellerId
      if (changes.commodity !== undefined) patch.commodity = changes.commodity
      if (changes.quantity !== undefined) patch.quantity_qtl = changes.quantity
      if (changes.rate !== undefined) patch.rate_per_qtl_paise = paise(changes.rate)
      if (changes.route !== undefined) patch.route = changes.route
      if (changes.stage) patch.stage = dbStage(changes.stage)
      if (changes.stage === 'Cancelled') { patch.cancelled_at = new Date().toISOString(); patch.cancelled_reason = changes.cancelledReason }
      const saved = await cloudAction(() => supabase!.from('deals').update(patch).eq('id', id), `Deal ${deal.dailySerial} saved to cloud.`)
      if (saved && (changes.quantity !== undefined || changes.rate !== undefined || changes.expectedPayment !== undefined)) {
        const expected = changes.expectedPayment ?? deal.expectedPayment
        const amount = paise((changes.quantity ?? deal.quantity) * (changes.rate ?? deal.rate))
        await cloudAction((ownerId) => supabase!.from('payment_obligations').upsert({ deal_id: id, owner_id: ownerId, ledger: 'commodity', amount_paise: amount, expected_payment_date: expected }, { onConflict: 'deal_id,ledger' }), `Deal ${deal.dailySerial} settlement updated.`)
      }
      return
    }
    setData({ ...data, deals: data.deals.map((item) => item.id === id ? { ...item, ...changes } : item) })
  }
  const advanceStage = (deal: Deal) => { if (deal.stage === 'Cancelled') return; const index = stages.indexOf(deal.stage); const next = stages[(index + 1) % stages.length]; updateDeal(deal.id, { stage: next }); setNotice(`Deal ${deal.dailySerial} moved to ${next}.`) }
  const cancelDeal = (id: string) => {
    const deal = data.deals.find((item) => item.id === id)
    if (!deal || deal.stage === 'Cancelled') return
    const reason = window.prompt('Cancellation reason (required):')?.trim()
    if (!reason) { setNotice('Cancellation was not saved because a reason is required.'); return }
    updateDeal(id, { stage: 'Cancelled', cancelledReason: reason })
    setNotice(`Deal ${deal.dailySerial} was cancelled. Its trips and payments remain in history, but it is excluded from totals.`)
  }

  const createParty = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = new FormData(event.currentTarget)
    const party: Party = { id: uid(), name: String(form.get('name')).trim(), phone: String(form.get('phone')), location: String(form.get('location')), trust: 'Normal', notes: String(form.get('notes')) }
    if (await cloudAction((ownerId) => supabase!.from('parties').insert({ id: party.id, owner_id: ownerId, name: party.name, phone: party.phone, location: party.location, notes: party.notes, trust: 'normal' }), `${party.name} added to the cloud workspace.`)) { setModal(returnToDeal ? 'deal' : null); setReturnToDeal(false); return }
    setData({ ...data, parties: [...data.parties, party] }); setNotice(`${party.name} was added. Choose it as buyer or seller on any Deal.`); setModal(returnToDeal ? 'deal' : null); setReturnToDeal(false)
  }
  const createDeal = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = new FormData(event.currentTarget); const date = String(form.get('dealDate'))
    const daily = data.deals.filter((deal) => deal.dealDate === date); const monthly = data.deals.filter((deal) => monthlyKey(deal.dealDate) === monthlyKey(date))
    const deal: Deal = { id: uid(), dealDate: date, dailySerial: Math.max(0, ...daily.map((d) => d.dailySerial)) + 1, monthlySerial: Math.max(0, ...monthly.map((d) => d.monthlySerial)) + 1, buyerId: String(form.get('buyer')), sellerId: String(form.get('seller')), commodity: String(form.get('commodity')), quantity: Number(form.get('quantity')), rate: Number(form.get('rate')), route: String(form.get('route') || ''), expectedPayment: String(form.get('expectedPayment') || date), stage: 'Matching', truck: '' }
    if (isSupabaseConfigured && supabase) {
      const result = await supabase.rpc('create_deal', { p_deal_date: date, p_buyer_party_id: deal.buyerId, p_seller_party_id: deal.sellerId, p_commodity: deal.commodity, p_quantity_qtl: deal.quantity, p_rate_per_qtl_paise: paise(deal.rate), p_route: deal.route, p_expected_payment_date: deal.expectedPayment })
      if (result.error) { setNotice(`Cloud save failed: ${result.error.message}`); return }
      if (dealDraft?.offerId) await supabase.from('offers').update({ status: 'converted' }).eq('id', dealDraft.offerId)
      if (dealDraft?.requirementId) await supabase.from('requirements').update({ status: 'converted' }).eq('id', dealDraft.requirementId)
      await reloadCloud(); setDealDraft(null); setSelectedDealId(result.data.id); setModal(null); setNotice(`Deal ${result.data.daily_serial} created securely in the cloud.`); return
    }
    setData({ ...data, deals: [...data.deals, deal], offers: dealDraft?.offerId ? data.offers.map((offer) => offer.id === dealDraft.offerId ? { ...offer, status: 'Converted' } : offer) : data.offers, requirements: dealDraft?.requirementId ? data.requirements.map((requirement) => requirement.id === dealDraft.requirementId ? { ...requirement, status: 'Converted' } : requirement) : data.requirements }); setDealDraft(null); setSelectedDealId(deal.id); setModal(null); setNotice(`Deal ${deal.dailySerial} created. Linked offers/requirements were marked converted.`)
  }
  const editDeal = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selectedDeal || selectedDeal.stage === 'Cancelled') return; const form = new FormData(event.currentTarget); updateDeal(selectedDeal.id, { buyerId: String(form.get('buyer')), sellerId: String(form.get('seller')), commodity: String(form.get('commodity')), quantity: Number(form.get('quantity')), rate: Number(form.get('rate')), route: String(form.get('route')), expectedPayment: String(form.get('expectedPayment')) }); setModal(null); setNotice(`Deal ${selectedDeal.dailySerial} updated. Its number, trips and payment history were preserved.`) }
  const addTrip = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); if (!selectedDeal || selectedDeal.stage === 'Cancelled') { setModal(null); setNotice('A cancelled Deal cannot receive a new truck.'); return }; const form = new FormData(event.currentTarget); const truck = String(form.get('truck'))
    const transporterId = String(form.get('transporter')); const truckRecord = data.trucks.find((item) => item.number === truck && item.transporterId === transporterId)
    if (!truckRecord) { setNotice('Choose a truck belonging to the selected transporter.'); return }
    if (await cloudAction((ownerId) => supabase!.from('deal_trips').insert({ id: uid(), owner_id: ownerId, deal_id: selectedDeal.id, transporter_id: transporterId, truck_id: truckRecord.id, route: selectedDeal.route, freight_paise: paise(Number(form.get('freight'))), assigned_at: String(form.get('assignedDate')), notes: String(form.get('notes')) }), 'Truck added to this Deal.')) { if (selectedDeal.stage === 'Matching') await updateDeal(selectedDeal.id, { stage: 'Truck Assigned' }); setModal(null); return }
    setData({ ...data, dealTrips: [...data.dealTrips, { id: uid(), dealId: selectedDeal.id, transporterId, truckNumber: truck, freight: Number(form.get('freight')), assignedDate: String(form.get('assignedDate')), notes: String(form.get('notes')) }], deals: data.deals.map((d) => d.id === selectedDeal.id && d.stage === 'Matching' ? { ...d, truck, stage: 'Truck Assigned' } : d) }); setModal(null); setNotice('Truck added to this Deal.');
  }
  const createPayment = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); const dealId = String(f.get('deal')); const ledger = String(f.get('ledger')) as LedgerType; const deal = data.deals.find((item) => item.id === dealId); if (!deal || deal.stage === 'Cancelled') { setModal(null); setNotice('A cancelled Deal retains prior payments but cannot receive a new one.'); return }; if (!obligation(deal, ledger)) { setNotice(`Set the ${ledger.toLowerCase()} obligation before recording its payment.`); return }; if (await cloudAction((ownerId) => supabase!.from('payment_entries').insert({ id: uid(), owner_id: ownerId, deal_id: dealId, ledger: dbLedger(ledger), amount_paise: paise(Number(f.get('amount'))), payment_date: String(f.get('date')), note: String(f.get('note')), recorded_by: ownerId }), `${ledger} payment recorded in cloud.`)) { setModal(null); return }; setData({ ...data, payments: [...data.payments, { id: uid(), dealId, ledger, amount: Number(f.get('amount')), date: String(f.get('date')), note: String(f.get('note')) }] }); setModal(null); setNotice(`${ledger} payment recorded; balance recalculated.`) }
  const editPayment = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!editingPayment) return; if (isSupabaseConfigured) { setEditingPaymentId(null); setModal(null); setNotice('Cloud payments are protected from editing. A separate audited reversal flow is required for corrections.'); return } const form = new FormData(event.currentTarget); const dealId = String(form.get('deal')); const ledger = String(form.get('ledger')) as LedgerType; setData({ ...data, payments: data.payments.map((payment) => payment.id === editingPayment.id ? { ...payment, dealId, ledger, amount: Number(form.get('amount')), date: String(form.get('date')), note: String(form.get('note')) } : payment) }); setEditingPaymentId(null); setModal(null); setNotice('Payment entry corrected. The ledger balance was recalculated.') }
  const saveCommission = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selectedDeal || selectedDeal.stage === 'Cancelled') return; const form = new FormData(event.currentTarget); const ledger = String(form.get('ledger')) as LedgerType; const next = { id: uid(), dealId: selectedDeal.id, ledger, amount: Number(form.get('amount')), expectedPayment: String(form.get('expectedPayment')) }; if (await cloudAction((ownerId) => supabase!.from('payment_obligations').upsert({ id: next.id, owner_id: ownerId, deal_id: next.dealId, ledger: dbLedger(ledger), amount_paise: paise(next.amount), expected_payment_date: next.expectedPayment }, { onConflict: 'deal_id,ledger' }), `${ledger} obligation saved to cloud.`)) { setModal(null); return }; setData({ ...data, obligations: [...data.obligations.filter((item) => !(item.dealId === selectedDeal.id && item.ledger === ledger)), next] }); setModal(null); setNotice(`${ledger} obligation saved.`) }
  const createTransporter = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const transporter = { id: uid(), name: String(form.get('name')).trim(), phone: String(form.get('phone')), routes: String(form.get('routes')), reliability: String(form.get('reliability')) as 'High' | 'Normal' | 'Watch' }; if (await cloudAction((ownerId) => supabase!.from('transporters').insert({ id: transporter.id, owner_id: ownerId, name: transporter.name, phone: transporter.phone, notes: transporter.routes, reliability: dbTrust(transporter.reliability) }), `${transporter.name} added to cloud Transport.`)) { setModal(null); return }; setData({ ...data, transporters: [...data.transporters, transporter] }); setModal(null); setNotice(`${transporter.name} added to Transport.`) }
  const createTruck = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const number = String(form.get('number')).trim().toUpperCase(); if (data.trucks.some((truck) => truck.number === number)) { setNotice('This truck number already exists.'); return }; const truck = { id: uid(), number, transporterId: String(form.get('transporter')), capacity: String(form.get('capacity')), driverPhone: String(form.get('driverPhone')) }; if (await cloudAction((ownerId) => supabase!.from('trucks').insert({ id: truck.id, owner_id: ownerId, transporter_id: truck.transporterId, registration_number: number, capacity_qtl: Number(truck.capacity) || null }), `${number} added to cloud Transport.`)) { setModal(null); return }; setData({ ...data, trucks: [...data.trucks, truck] }); setModal(null); setNotice(`${number} added to Transport.`) }
  const createTodo = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const text = String(form.get('text')).trim(); if (!text) return; const todo = { id: uid(), text, done: false, due: String(form.get('due')) }; if (await cloudAction((ownerId) => supabase!.from('todos').insert({ id: todo.id, owner_id: ownerId, text, due_date: todo.due || null }), 'Follow-up saved to cloud.')) { setModal(null); return }; setData({ ...data, todos: [...data.todos, todo] }); setModal(null); setNotice('Follow-up added.') }
  const toggleTodo = async (id: string) => { const todo = data.todos.find((item) => item.id === id); if (!todo) return; if (isSupabaseConfigured && supabase) { await cloudAction(() => supabase!.from('todos').update({ completed_at: todo.done ? null : new Date().toISOString() }).eq('id', id), 'Follow-up updated.'); return } setData({ ...data, todos: data.todos.map((item) => item.id === id ? { ...item, done: !item.done } : item) }) }
  const deleteTodo = async (id: string) => { if (!window.confirm('Delete this follow-up?')) return; if (isSupabaseConfigured && supabase) { if (await cloudAction(() => supabase!.from('todos').delete().eq('id', id), 'Follow-up deleted.')) return } setData({ ...data, todos: data.todos.filter((item) => item.id !== id) }) }
  const deleteTransporter = async (id: string) => { if (!window.confirm('Delete this transporter? This cannot be undone.')) return; if (isSupabaseConfigured && supabase) { if (await cloudAction(() => supabase!.from('transporters').delete().eq('id', id), 'Transporter deleted.')) return } setData({ ...data, transporters: data.transporters.filter((item) => item.id !== id) }) }
  const deleteParty = async (id: string) => { if (!window.confirm('Delete this party? This cannot be undone, and will fail if the party has any Deals, offers, or requirements on record.')) return; if (isSupabaseConfigured && supabase) { if (await cloudAction(() => supabase!.from('parties').delete().eq('id', id), 'Party deleted.')) { setSelectedPartyId(null); return } } setData({ ...data, parties: data.parties.filter((item) => item.id !== id) }); setSelectedPartyId(null) }
  const exportRegister = (records: Deal[], filename: string) => { const headers = ['Date', 'Daily No.', 'Monthly No.', 'Buyer', 'Seller', 'Commodity', 'Quantity Qtl', 'Rate', 'Value', 'Route', 'Stage', 'Commodity Due', 'Buyer Commission Due', 'Seller Commission Due']; const rows = records.map((deal) => [deal.dealDate, deal.dailySerial, deal.monthlySerial, name(deal.buyerId), name(deal.sellerId), deal.commodity, deal.quantity, deal.rate, dealValue(deal), deal.route, deal.stage, deal.stage === 'Cancelled' ? 'Excluded' : dueFor(deal, 'Commodity'), deal.stage === 'Cancelled' ? 'Excluded' : dueFor(deal, 'Buyer Commission'), deal.stage === 'Cancelled' ? 'Excluded' : dueFor(deal, 'Seller Commission')]); const csv = [headers, ...rows].map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); link.download = filename; link.click(); URL.revokeObjectURL(link.href); setNotice('Excel-compatible register exported.') }
  const createMarketRecord = async (event: FormEvent<HTMLFormElement>, kind: 'offer' | 'requirement') => { event.preventDefault(); const form = new FormData(event.currentTarget); const partyId = String(form.get('party')); const commodity = String(form.get('commodity')); const quantity = Number(form.get('quantity')); const rate = Number(form.get('rate')); const location = String(form.get('location')); if (isSupabaseConfigured && supabase) { const saved = await cloudAction((ownerId) => kind === 'offer' ? supabase!.from('offers').insert({ id: uid(), owner_id: ownerId, seller_party_id: partyId, commodity, quantity_qtl: quantity, rate_per_qtl_paise: paise(rate), location }) : supabase!.from('requirements').insert({ id: uid(), owner_id: ownerId, buyer_party_id: partyId, commodity, quantity_qtl: quantity, target_rate_paise: paise(rate), delivery_location: location }), `${kind === 'offer' ? 'Seller offer' : 'Buyer requirement'} saved to cloud.`); if (saved) { setModal(null); return } } if (kind === 'offer') setData({ ...data, offers: [...data.offers, { id: uid(), sellerId: partyId, commodity, quantity, rate, location, status: 'Open' }] }); else setData({ ...data, requirements: [...data.requirements, { id: uid(), buyerId: partyId, commodity, quantity, targetRate: rate, deliveryLocation: location, status: 'Open' }] }); setModal(null); setNotice(`${kind === 'offer' ? 'Seller offer' : 'Buyer requirement'} saved. It remains separate until you create a Deal.`) }
  const openDeal = (id: string) => { setSelectedDealId(id); setPage('Deals') }
  const startDealFromMatch = (offerId: string, requirementId: string) => { const offer = data.offers.find((item) => item.id === offerId); const requirement = data.requirements.find((item) => item.id === requirementId); if (!offer || !requirement) return; setDealDraft({ buyerId: requirement.buyerId, sellerId: offer.sellerId, commodity: offer.commodity, quantity: Math.min(offer.quantity, requirement.quantity), rate: offer.rate, offerId, requirementId }); setModal('deal') }
  const setMarketStatus = async (kind: 'offer' | 'requirement', id: string, status: 'Open' | 'Converted' | 'Closed') => { if (isSupabaseConfigured && supabase) { await cloudAction(() => supabase!.from(kind === 'offer' ? 'offers' : 'requirements').update({ status: status.toLowerCase() }).eq('id', id), `${kind === 'offer' ? 'Offer' : 'Requirement'} marked ${status.toLowerCase()}.`); return } if (kind === 'offer') setData({ ...data, offers: data.offers.map((offer) => offer.id === id ? { ...offer, status } : offer) }); else setData({ ...data, requirements: data.requirements.map((requirement) => requirement.id === id ? { ...requirement, status } : requirement) }); setNotice(`${kind === 'offer' ? 'Offer' : 'Requirement'} marked ${status.toLowerCase()}.`) }
  const toggleTheme = () => { const next = !darkMode; setDarkMode(next); window.localStorage.setItem('shree-balaje-theme', next ? 'dark' : 'light') }

  const dealRows = (records: Deal[]) => <div className="table-wrap"><table><thead><tr><th>Deal</th><th>Buyer / Seller</th><th>Commodity</th><th>Status</th><th>Outstanding</th><th/></tr></thead><tbody>{records.map((deal) => <tr key={deal.id}><td><strong>Daily {deal.dailySerial}</strong><small>{formatDate(deal.dealDate)} · M{deal.monthlySerial}</small></td><td><strong>{name(deal.buyerId)}</strong><small>{name(deal.sellerId)}</small></td><td>{deal.commodity}<small>{deal.quantity} Qtl · {currency.format(deal.rate)}/Qtl</small></td><td><button className={`status status-${deal.stage.toLowerCase().replace(' ', '-')}`} disabled={deal.stage === 'Cancelled'} onClick={() => advanceStage(deal)} title="Click to move to the next stage">{deal.stage}</button></td><td>{deal.stage === 'Cancelled' ? 'Excluded' : currency.format(due(deal))}</td><td><button className="text-button" onClick={() => openDeal(deal.id)}>Open →</button></td></tr>)}</tbody></table></div>
  // Trimmed view for the Dashboard only: Serial, Buyer/Seller (larger), Quantity, Truck, Phone. Full detail lives on the Deals page.
  const dashboardDealRows = (records: Deal[]) => <div className="table-wrap"><table><thead><tr><th>#</th><th>Buyer / Seller</th><th>Quantity</th><th>Truck</th><th>Phone</th><th/></tr></thead><tbody>{records.map((deal) => <tr key={deal.id}><td><strong>{deal.dailySerial}</strong></td><td><strong className="dashboard-party-name">{name(deal.buyerId)}</strong><strong className="dashboard-party-name">{name(deal.sellerId)}</strong></td><td>{deal.quantity} Qtl</td><td>{deal.truck || '—'}</td><td>{phone(deal.buyerId)} / {phone(deal.sellerId)}</td><td><button className="text-button" onClick={() => openDeal(deal.id)}>Open →</button></td></tr>)}</tbody></table></div>
  const dashboard = <><section className="panel page-panel"><div className="panel-heading"><div><p className="eyebrow">WORKING NOW</p><h2>Active Deals</h2><p className="section-subtitle">Open a Deal to add its truck, record payments, and advance its status.</p></div><button className="primary-button" onClick={() => setModal('deal')}>+ New Deal</button></div>{dashboardDealRows(active)}</section><section className="bottom-grid"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">TODAY</p><h2>To-Do</h2></div><button className="text-button" onClick={() => setPage('To-Do')}>Open →</button></div><div className="todo-list">{data.todos.filter((todo) => !todo.done).slice(0, 5).map((todo) => <label key={todo.id}><input type="checkbox" checked={todo.done} onChange={() => void toggleTodo(todo.id)}/><span>{todo.text}</span><small>{formatDate(todo.due)}</small></label>)}</div></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">ATTENTION</p><h2>Overdue Payments</h2></div><button className="text-button" onClick={() => setPage('Payments')}>Open →</button></div>{overdue.length ? overdue.map((deal) => <div className="attention-row" key={deal.id}><div><strong>Deal {deal.dailySerial} · {name(deal.buyerId)}</strong><p>{currency.format(due(deal))} overdue since {formatDate(deal.expectedPayment)}</p></div></div>) : <div className="empty-callout">No overdue payments.</div>}</section></section></>
  let content: React.ReactNode = dashboard
  if (page === 'Deals') content = <Section title="Deals" subtitle="Create the deal once; manage all later action from its Deal record." action="+ New Deal" onAction={() => setModal('deal')}>{selectedDeal ? <DealWorkspace deal={selectedDeal} trips={data.dealTrips.filter((trip) => trip.dealId === selectedDeal.id)} name={name} due={due(selectedDeal)} buyerCommission={dueFor(selectedDeal, 'Buyer Commission')} sellerCommission={dueFor(selectedDeal, 'Seller Commission')} onClose={() => setSelectedDealId(null)} onStage={(stage) => updateDeal(selectedDeal.id, { stage })} onEdit={() => setModal('edit-deal')} onTrip={() => setModal('trip')} onPayment={() => setModal('payment')} onCommission={() => setModal('commission')} onCancel={() => cancelDeal(selectedDeal.id)} /> : dealRows(data.deals)}</Section>
  if (page === 'Parties') content = <Section title="Parties" subtitle="Party details are stored once. Buyer and seller are Deal roles, not party types." action="+ Add Party" onAction={() => setModal('party')}>{selectedParty ? <PartyProfile party={selectedParty} deals={data.deals.filter((deal) => deal.buyerId === selectedParty.id || deal.sellerId === selectedParty.id)} outstanding={(deal) => due(deal)} onClose={() => setSelectedPartyId(null)} onOpenDeal={openDeal} onDelete={() => void deleteParty(selectedParty.id)} /> : <div className="table-wrap"><table><thead><tr><th>Party</th><th>Phone</th><th>Location</th><th>Trust</th><th>Deals</th><th/></tr></thead><tbody>{data.parties.map((party) => <tr key={party.id}><td><strong>{party.name}</strong><small>{party.notes || 'No notes'}</small></td><td>{party.phone || '—'}</td><td>{party.location || '—'}</td><td>{party.trust}</td><td>{data.deals.filter((d) => d.buyerId === party.id || d.sellerId === party.id).length}</td><td><button className="text-button" onClick={() => setSelectedPartyId(party.id)}>Open →</button></td></tr>)}</tbody></table></div>}</Section>
  if (page === 'Offers & Requirements') { const matches = data.offers.filter((offer) => offer.status === 'Open').flatMap((offer) => data.requirements.filter((requirement) => requirement.status === 'Open' && requirement.commodity === offer.commodity).map((requirement) => ({ offer, requirement }))); content = <Section title="Offers & Requirements" subtitle="Record market availability and demand, then convert a reviewed match into a prefilled Deal."><div className="split-actions"><button className="primary-button" onClick={() => setModal('offer')}>+ Seller Offer</button><button className="secondary-button" onClick={() => setModal('requirement')}>+ Buyer Requirement</button></div><div className="two-table"><div><h3>Seller offers</h3>{data.offers.map((offer) => <article className="record-card" key={offer.id}><strong>{offer.commodity} · {offer.quantity} Qtl</strong><p>{name(offer.sellerId)} · {offer.location}</p><span>{currency.format(offer.rate)}/Qtl · {offer.status}</span><select value={offer.status} onChange={(event) => setMarketStatus('offer', offer.id, event.target.value as 'Open' | 'Converted' | 'Closed')}><option>Open</option><option>Converted</option><option>Closed</option></select></article>)}</div><div><h3>Buyer requirements</h3>{data.requirements.map((requirement) => <article className="record-card" key={requirement.id}><strong>{requirement.commodity} · {requirement.quantity} Qtl</strong><p>{name(requirement.buyerId)} · {requirement.deliveryLocation}</p><span>Target {currency.format(requirement.targetRate)}/Qtl · {requirement.status}</span><select value={requirement.status} onChange={(event) => setMarketStatus('requirement', requirement.id, event.target.value as 'Open' | 'Converted' | 'Closed')}><option>Open</option><option>Converted</option><option>Closed</option></select></article>)}</div></div><div className="match-note">{matches.length ? <><strong>{matches.length} possible match{matches.length === 1 ? '' : 'es'}.</strong>{matches.map(({ offer, requirement }) => <div key={`${offer.id}-${requirement.id}`}><span>{name(offer.sellerId)} → {name(requirement.buyerId)} · {offer.commodity} · {Math.min(offer.quantity, requirement.quantity)} Qtl</span><button className="text-button" onClick={() => startDealFromMatch(offer.id, requirement.id)}>Create prefilled Deal →</button></div>)}</> : 'No open commodity matches currently.'}</div></Section> }
  if (page === 'Transport') { const freightTrips = data.dealTrips.filter((trip) => data.deals.find((deal) => deal.id === trip.dealId)?.stage !== 'Cancelled'); content = <Section title="Transport" subtitle="Transport is added to the Deal; this screen keeps transporter, truck and freight memory easy to find."><div className="split-actions"><button className="primary-button" onClick={() => setModal('transporter')}>+ Add Transporter</button><button className="secondary-button" onClick={() => setModal('truck')}>+ Add Truck</button></div><div className="two-table"><div><h3>Transporters</h3>{data.transporters.map((t) => <article className="record-card" key={t.id}><strong>{t.name}</strong><p>{t.routes || 'Routes not entered'}</p><span>{t.phone || 'No phone'} · {t.reliability} reliability</span><button type="button" className="danger-link small" onClick={() => void deleteTransporter(t.id)}>Delete</button></article>)}</div><div><h3>Known trucks</h3>{data.trucks.map((t) => <article className="record-card" key={t.id}><strong>{t.number}</strong><p>{data.transporters.find((x) => x.id === t.transporterId)?.name ?? 'Unknown transporter'}</p><span>{t.capacity || 'Capacity not entered'} · Driver phone: {t.driverPhone || 'Not entered'}</span></article>)}</div></div><div className="two-table"><div><h3>Freight history</h3>{freightTrips.length ? freightTrips.map((trip) => { const deal = data.deals.find((item) => item.id === trip.dealId); const transporter = data.transporters.find((item) => item.id === trip.transporterId); return <article className="record-card" key={trip.id}><strong>{transporter?.name ?? 'Unknown transporter'} · {deal?.route ?? 'Route not entered'}</strong><p>{trip.truckNumber} · Deal {deal?.dailySerial ?? '—'} · {formatDate(trip.assignedDate)}</p><span>Freight {currency.format(trip.freight)}</span></article> }) : <div className="empty-callout">Freight history appears after a truck is assigned to a Deal.</div>}</div></div></Section> }
  if (page === 'Payments') { const dueItems = data.deals.filter((deal) => deal.stage !== 'Cancelled').flatMap((deal) => (['Commodity', 'Buyer Commission', 'Seller Commission'] as LedgerType[]).map((ledger) => ({ deal, ledger, obligation: obligation(deal, ledger), amount: dueFor(deal, ledger) })).filter((item) => item.obligation && item.amount > 0)).sort((a, b) => String(a.obligation?.expectedPayment).localeCompare(String(b.obligation?.expectedPayment))); content = <Section title="Payments & Commissions" subtitle="Commodity, buyer commission and seller commission are separate ledgers." action="+ Record Payment" onAction={() => setModal('payment')}><div className="ledger-cards"><Metric title="Commodity outstanding" value={currency.format(data.deals.filter((deal) => deal.stage !== 'Cancelled').reduce((sum, deal) => sum + dueFor(deal, 'Commodity'), 0))}/><Metric title="Buyer commission due" value={currency.format(data.deals.filter((deal) => deal.stage !== 'Cancelled').reduce((sum, deal) => sum + dueFor(deal, 'Buyer Commission'), 0))}/><Metric title="Seller commission due" value={currency.format(data.deals.filter((deal) => deal.stage !== 'Cancelled').reduce((sum, deal) => sum + dueFor(deal, 'Seller Commission'), 0))}/></div><div className="two-table"><div><h3>Due payments</h3>{dueItems.length ? dueItems.map(({ deal, ledger, obligation: item, amount }) => <article className="record-card" key={`${deal.id}-${ledger}`}><strong>{ledger} · Deal {deal.dailySerial}</strong><p>{name(deal.buyerId)} / {name(deal.sellerId)}</p><span>{currency.format(amount)} due {formatDate(item?.expectedPayment)} {item && item.expectedPayment < today ? '· OVERDUE' : ''}</span><button className="text-button" onClick={() => openDeal(deal.id)}>Open Deal →</button></article>) : <div className="empty-callout">No payment is currently due.</div>}</div><div><h3>Recorded payments</h3>{data.payments.length ? data.payments.slice().sort((a, b) => b.date.localeCompare(a.date)).map((payment) => { const deal = data.deals.find((item) => item.id === payment.dealId); return <article className="record-card" key={payment.id}><strong>{payment.ledger} · {currency.format(payment.amount)}</strong><p>Deal {deal?.dailySerial ?? '—'} · {formatDate(payment.date)} · {payment.note || 'No note'}</p><button className="text-button" onClick={() => { setEditingPaymentId(payment.id); setModal('edit-payment') }}>Edit payment →</button></article> }) : <div className="empty-callout">No payment entries yet.</div>}</div></div>{dealRows(data.deals)}</Section> }
  if (page === 'Daily Register') { const records = data.deals.filter((d) => d.dealDate === today); const live = records.filter((d) => d.stage !== 'Cancelled'); const totalValue = live.reduce((sum, deal) => sum + dealValue(deal), 0); const totalQty = live.reduce((sum, deal) => sum + deal.quantity, 0); const totalDue = live.reduce((sum, deal) => sum + due(deal), 0); content = <Section title="Daily Register" subtitle="Read-only closing summary of today's business — for record-keeping, not editing. Open a Deal from the Deals page to make changes." action="Export Excel" onAction={() => exportRegister(records, `daily-register-${today}.csv`)}><div className="ledger-cards"><Metric title="Deals today" value={String(records.length)}/><Metric title="Total quantity" value={`${totalQty} Qtl`}/><Metric title="Total value" value={currency.format(totalValue)}/><Metric title="Commodity due" value={currency.format(totalDue)}/></div><div className="table-wrap"><table><thead><tr><th>#</th><th>Buyer</th><th>Seller</th><th>Commodity</th><th>Qtl</th><th>Rate</th><th>Value</th><th>Stage</th><th>Due</th></tr></thead><tbody>{records.length ? records.map((deal) => <tr key={deal.id}><td>{deal.dailySerial}</td><td>{name(deal.buyerId)}</td><td>{name(deal.sellerId)}</td><td>{deal.commodity}</td><td>{deal.quantity}</td><td>{currency.format(deal.rate)}</td><td>{deal.stage === 'Cancelled' ? 'Excluded' : currency.format(dealValue(deal))}</td><td>{deal.stage}</td><td>{deal.stage === 'Cancelled' ? 'Excluded' : currency.format(due(deal))}</td></tr>) : <tr><td colSpan={9}>No Deals recorded for today yet.</td></tr>}</tbody></table></div></Section> }
  if (page === 'Monthly Ledger') { const records = data.deals.filter((deal) => monthlyKey(deal.dealDate) === monthlyKey(today)); const included = records.filter((deal) => deal.stage !== 'Cancelled'); content = <Section title="Monthly Ledger" subtitle="Derived from underlying records. Cancelled Deals remain visible but are excluded from totals." action="Print / Save PDF" onAction={() => window.print()}><div className="ledger-cards"><Metric title="Business value" value={currency.format(included.reduce((sum, deal) => sum + dealValue(deal), 0))}/><Metric title="Commodity due" value={currency.format(included.reduce((sum, deal) => sum + dueFor(deal, 'Commodity'), 0))}/><Metric title="Commission due" value={currency.format(included.reduce((sum, deal) => sum + dueFor(deal, 'Buyer Commission') + dueFor(deal, 'Seller Commission'), 0))}/></div>{dealRows(records)}</Section> }
  if (page === 'To-Do') content = <Section title="To-Do" subtitle="Simple follow-ups for the broker’s day." action="+ Add Follow-up" onAction={() => setModal('todo')}><div className="todo-list">{data.todos.map((todo) => <label key={todo.id}><input type="checkbox" checked={todo.done} onChange={() => void toggleTodo(todo.id)}/><span>{todo.text}</span><small>{formatDate(todo.due)}</small><button type="button" className="danger-link small" onClick={() => void deleteTodo(todo.id)}>Delete</button></label>)}</div></Section>
  if (page === 'Reports') { const openDeals = data.deals.filter((deal) => !['Closed', 'Cancelled'].includes(deal.stage)); const cancelled = data.deals.filter((deal) => deal.stage === 'Cancelled'); content = <Section title="Reports & Exports" subtitle="Practical business records for review, filing and sharing."><div className="report-grid"><Report title="Full Deal Register" text={`${data.deals.length} records, including cancelled history.`} action="Export Excel" onClick={() => exportRegister(data.deals, 'shree-balaje-deal-register.csv')}/><Report title="Outstanding Commodity" text={currency.format(data.deals.filter((deal) => deal.stage !== 'Cancelled').reduce((sum, deal) => sum + dueFor(deal, 'Commodity'), 0))} action="Open Payments" onClick={() => setPage('Payments')}/><Report title="Active Deals" text={`${openDeals.length} operational Deals need attention.`} action="Open Deals" onClick={() => setPage('Deals')}/><Report title="Cancelled Deals" text={`${cancelled.length} preserved historical record${cancelled.length === 1 ? '' : 's'}.`} action="Open Deals" onClick={() => setPage('Deals')}/><Report title="Monthly Accounting" text="Date-wise ledger suitable for print or Save as PDF." action="Open Monthly Ledger" onClick={() => setPage('Monthly Ledger')}/><Report title="Freight History" text="Transporter and route freight memory from Deal trips." action="Open Transport" onClick={() => setPage('Transport')}/></div></Section> }

  const modalTitle = modal === 'deal' ? 'New Deal' : modal === 'edit-deal' ? 'Edit Deal' : modal === 'edit-payment' ? 'Edit Payment' : modal === 'party' ? 'New Party' : modal === 'trip' ? 'Add Truck to Deal' : modal === 'offer' ? 'Record Seller Offer' : modal === 'requirement' ? 'Record Buyer Requirement' : modal === 'commission' ? 'Set Commission Obligation' : modal === 'transporter' ? 'Add Transporter' : modal === 'truck' ? 'Add Truck' : modal === 'todo' ? 'Add Follow-up' : 'Record Payment'
  return <div className={`app-shell ${darkMode ? 'dark' : ''}`}><aside className="sidebar"><div className="brand"><span className="brand-mark">SB</span><span>Shree Balaje<small>Broker</small></span></div><nav>{nav.map((item) => <button key={item} className={page === item ? 'nav-item active' : 'nav-item'} onClick={() => { setPage(item); if (item !== 'Deals') setSelectedDealId(null) }}><span>◇</span>{item}</button>)}</nav><div className="sidebar-footer">Local workspace<br/><small>Cloud connection ready</small></div></aside><main><header className="topbar"><div><p className="eyebrow">{todayDisplay()}</p><h1>{page === 'Dashboard' ? "Today's Business" : page}</h1></div><div className="header-actions"><button className="secondary-button" onClick={toggleTheme}>{darkMode ? 'Light mode' : 'Dark mode'}</button><button className="primary-button" onClick={() => setModal('deal')}>+ New Deal</button></div></header>{notice && <div className="toast">{notice}<button onClick={() => setNotice('')}>×</button></div>}{content}</main>{modal && <Modal title={modalTitle} onClose={() => setModal(null)}>{modal === 'deal' && <DealForm parties={data.parties} draft={dealDraft} onSubmit={createDeal} onAddParty={() => { setReturnToDeal(true); setModal('party') }}/>} {modal === 'edit-deal' && selectedDeal && <EditDealForm deal={selectedDeal} parties={data.parties} onSubmit={editDeal}/>} {modal === 'party' && <PartyForm onSubmit={createParty}/>} {modal === 'trip' && <TripForm transporters={data.transporters} trucks={data.trucks} onSubmit={addTrip}/>} {modal === 'payment' && <PaymentForm deals={data.deals} selectedDealId={selectedDealId} onSubmit={createPayment}/>} {modal === 'edit-payment' && editingPayment && <PaymentForm deals={data.deals} payment={editingPayment} onSubmit={editPayment}/>} {modal === 'commission' && <CommissionForm onSubmit={saveCommission}/>} {modal === 'transporter' && <TransporterForm onSubmit={createTransporter}/>} {modal === 'truck' && <TruckForm transporters={data.transporters} onSubmit={createTruck}/>} {modal === 'todo' && <TodoForm onSubmit={createTodo}/>} {(modal === 'offer' || modal === 'requirement') && <MarketForm kind={modal} parties={data.parties} onSubmit={(event) => createMarketRecord(event, modal)}/>}</Modal>}</div>
}

function Section({ title, subtitle, action, onAction, children }: { title: string; subtitle: string; action?: string; onAction?: () => void; children: React.ReactNode }) { return <section className="panel page-panel"><div className="panel-heading"><div><p className="eyebrow">BUSINESS WORKSPACE</p><h2>{title}</h2><p className="section-subtitle">{subtitle}</p></div>{action && <button className="primary-button" onClick={onAction}>{action}</button>}</div>{children}</section> }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="modal-backdrop"><section className="deal-modal" role="dialog" aria-modal="true"><div className="modal-heading"><div><p className="eyebrow">DEAL WORKSPACE</p><h2>{title}</h2></div><button className="close-button" onClick={onClose}>×</button></div>{children}</section></div> }
function DealForm({ parties, draft, onSubmit, onAddParty }: { parties: Party[]; draft: { buyerId?: string; sellerId?: string; commodity?: string; quantity?: number; rate?: number } | null; onSubmit: (e: FormEvent<HTMLFormElement>) => void; onAddParty: () => void }) { return <form onSubmit={onSubmit}><div className="form-grid"><label>Deal date<input name="dealDate" type="date" defaultValue={today} required/></label><label>Buyer <select name="buyer" defaultValue={draft?.buyerId} required>{parties.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Seller <select name="seller" defaultValue={draft?.sellerId} required>{parties.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button type="button" className="secondary-button" onClick={onAddParty}>+ Add new party</button><label>Commodity<select name="commodity" defaultValue={draft?.commodity ?? 'Paddy'}><option>Paddy</option><option>Wheat</option><option>Rice</option></select></label><label>Quantity (Qtl)<input name="quantity" type="number" min="0.01" step="0.01" defaultValue={draft?.quantity} required/></label><label>Rate (₹/Qtl) <span className="optional-tag">(optional)</span><input name="rate" type="number" min="0" defaultValue={draft?.rate}/></label><label>Route <span className="optional-tag">(optional)</span><input name="route"/></label><label>Expected payment <span className="optional-tag">(optional)</span><input name="expectedPayment" type="date"/></label></div><div className="form-note">This captures the deal once. Add transport, payment and stage updates from the Deal afterwards.</div><div className="form-actions"><button className="primary-button">Create Deal</button></div></form> }
function EditDealForm({ deal, parties, onSubmit }: { deal: Deal; parties: Party[]; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form onSubmit={onSubmit}><div className="form-grid"><label>Buyer<select name="buyer" defaultValue={deal.buyerId}>{parties.map((party) => <option key={party.id} value={party.id}>{party.name}</option>)}</select></label><label>Seller<select name="seller" defaultValue={deal.sellerId}>{parties.map((party) => <option key={party.id} value={party.id}>{party.name}</option>)}</select></label><label>Commodity<select name="commodity" defaultValue={deal.commodity}><option>Paddy</option><option>Wheat</option><option>Rice</option></select></label><label>Quantity (Qtl)<input name="quantity" type="number" min="0.01" step="0.01" defaultValue={deal.quantity} required/></label><label>Rate (₹/Qtl)<input name="rate" type="number" min="0" defaultValue={deal.rate} required/></label><label>Route<input name="route" defaultValue={deal.route} required/></label><label>Expected payment<input name="expectedPayment" type="date" defaultValue={deal.expectedPayment} required/></label></div><div className="form-note">Deal number, date, existing payments and transport history cannot be overwritten here.</div><div className="form-actions"><button className="primary-button">Save Deal Changes</button></div></form> }
function PartyForm({ onSubmit }: { onSubmit: (e: FormEvent<HTMLFormElement>) => void }) { return <form onSubmit={onSubmit}><div className="form-grid"><label>Party name<input name="name" required/></label><label>Phone<input name="phone"/></label><label>Location<input name="location"/></label><label className="span-two">Notes<textarea name="notes"/></label></div><div className="form-actions"><button className="primary-button">Save Party</button></div></form> }
function MarketForm({ kind, parties, onSubmit }: { kind: 'offer' | 'requirement'; parties: Party[]; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form onSubmit={onSubmit}><div className="form-grid"><label>{kind === 'offer' ? 'Seller' : 'Buyer'}<select name="party">{parties.map((party) => <option key={party.id} value={party.id}>{party.name}</option>)}</select></label><label>Commodity<select name="commodity"><option>Paddy</option><option>Wheat</option><option>Rice</option></select></label><label>Quantity (Qtl)<input name="quantity" type="number" min="0.01" step="0.01" required/></label><label>{kind === 'offer' ? 'Rate' : 'Target rate'} (₹/Qtl)<input name="rate" type="number" min="0" required/></label><label className="span-two">{kind === 'offer' ? 'Location' : 'Delivery location'}<input name="location" required/></label></div><div className="form-note">This remains separate until you explicitly create a Deal.</div><div className="form-actions"><button className="primary-button">Save {kind === 'offer' ? 'Offer' : 'Requirement'}</button></div></form> }
function TripForm({ transporters, trucks, onSubmit }: { transporters: { id: string; name: string }[]; trucks: { number: string; transporterId: string }[]; onSubmit: (e: FormEvent<HTMLFormElement>) => void }) { return <form onSubmit={onSubmit}><div className="form-grid"><label>Transporter<select name="transporter">{transporters.map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Truck<select name="truck">{trucks.map((t) => <option key={t.number} value={t.number}>{t.number}</option>)}</select></label><label>Freight (₹)<input name="freight" type="number" min="0" required/></label><label>Assigned date<input name="assignedDate" type="date" defaultValue={today} required/></label><label className="span-two">Notes<textarea name="notes"/></label></div><div className="form-actions"><button className="primary-button">Add Truck</button></div></form> }
function Metric({ title, value }: { title: string; value: string }) { return <article className="summary-card"><div><p>{title}</p><strong>{value}</strong></div></article> }
function Report({ title, text, action, onClick }: { title: string; text: string; action: string; onClick: () => void }) { return <article className="report-card"><h3>{title}</h3><p>{text}</p><button className="secondary-button" onClick={onClick}>{action}</button></article> }
function PaymentForm({ deals, selectedDealId, payment, onSubmit }: { deals: Deal[]; selectedDealId?: string | null; payment?: { dealId: string; ledger: LedgerType; amount: number; date: string; note: string }; onSubmit: (e: FormEvent<HTMLFormElement>) => void }) { return <form onSubmit={onSubmit}><div className="form-grid"><label>Deal<select name="deal" defaultValue={payment?.dealId ?? selectedDealId ?? undefined}>{deals.filter((deal) => deal.stage !== 'Cancelled' || deal.id === payment?.dealId).map((d) => <option key={d.id} value={d.id}>Daily {d.dailySerial} · {d.commodity}</option>)}</select></label><label>Ledger<select name="ledger" defaultValue={payment?.ledger}><option>Commodity</option><option>Buyer Commission</option><option>Seller Commission</option></select></label><label>Amount (₹)<input name="amount" type="number" min="1" defaultValue={payment?.amount} required/></label><label>Date<input name="date" type="date" defaultValue={payment?.date ?? today} required/></label><label className="span-two">Note<textarea name="note" defaultValue={payment?.note}/></label></div><div className="form-note">Partial entries are unlimited. Each ledger balance is calculated from its obligation and payment history.</div><div className="form-actions"><button className="primary-button">{payment ? 'Save Correction' : 'Save Payment'}</button></div></form> }
function CommissionForm({ onSubmit }: { onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form onSubmit={onSubmit}><div className="form-grid"><label>Commission due from<select name="ledger"><option>Buyer Commission</option><option>Seller Commission</option></select></label><label>Amount (₹)<input name="amount" type="number" min="0" required/></label><label>Expected payment<input name="expectedPayment" type="date" defaultValue={today} required/></label></div><div className="form-note">Commission is intentionally separate from the commodity settlement.</div><div className="form-actions"><button className="primary-button">Save Commission</button></div></form> }
function TransporterForm({ onSubmit }: { onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form onSubmit={onSubmit}><div className="form-grid"><label>Transporter name<input name="name" required/></label><label>Phone<input name="phone"/></label><label>Routes<input name="routes" placeholder="e.g. Buxar – Patna"/></label><label>Reliability<select name="reliability"><option>Normal</option><option>High</option><option>Watch</option></select></label></div><div className="form-actions"><button className="primary-button">Save Transporter</button></div></form> }
function TruckForm({ transporters, onSubmit }: { transporters: { id: string; name: string }[]; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form onSubmit={onSubmit}><div className="form-grid"><label>Truck number<input name="number" placeholder="BR 01 GK 4821" required/></label><label>Transporter<select name="transporter">{transporters.map((transporter) => <option key={transporter.id} value={transporter.id}>{transporter.name}</option>)}</select></label><label>Capacity (Qtl)<input name="capacity" type="number" min="0"/></label><label>Driver phone (optional)<input name="driverPhone" type="tel"/></label></div><div className="form-note">Driver name is intentionally not stored.</div><div className="form-actions"><button className="primary-button">Save Truck</button></div></form> }
function TodoForm({ onSubmit }: { onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form onSubmit={onSubmit}><div className="form-grid"><label className="span-two">Follow-up<input name="text" placeholder="e.g. Confirm unloading" required/></label><label>Due date<input name="due" type="date" defaultValue={today} required/></label></div><div className="form-actions"><button className="primary-button">Save Follow-up</button></div></form> }
function DealWorkspace({ deal, trips, name, due, buyerCommission, sellerCommission, onClose, onStage, onEdit, onTrip, onPayment, onCommission, onCancel }: { deal: Deal; trips: { id: string; truckNumber: string; freight: number; assignedDate: string }[]; name: (id: string) => string; due: number; buyerCommission: number; sellerCommission: number; onClose: () => void; onStage: (stage: DealStage) => void; onEdit: () => void; onTrip: () => void; onPayment: () => void; onCommission: () => void; onCancel: () => void }) { const cancelled = deal.stage === 'Cancelled'; return <div><div className="ledger-cards"><Metric title="Commodity due" value={currency.format(due)}/><Metric title="Buyer commission due" value={currency.format(buyerCommission)}/><Metric title="Seller commission due" value={currency.format(sellerCommission)}/></div><div className="two-table"><div><h3>Deal {deal.dailySerial}</h3><article className="record-card"><strong>{name(deal.buyerId)} ← {name(deal.sellerId)}</strong><p>{deal.commodity} · {deal.quantity} Qtl · {currency.format(dealValue(deal))}</p><span>{cancelled ? `Cancelled: ${deal.cancelledReason}` : `Commodity due: ${currency.format(due)}`}</span></article>{cancelled ? <div className="empty-callout">Cancelled Deals are retained as history. Their existing payments and trips remain visible, but new changes are blocked.</div> : <><label>Stage<select value={deal.stage} onChange={(e) => onStage(e.target.value as DealStage)}>{stages.map((stage) => <option key={stage}>{stage}</option>)}</select></label><button className="secondary-button" onClick={onEdit}>Edit Deal</button><button className="secondary-button" onClick={onCommission}>Set commission</button><button className="secondary-button" onClick={onPayment}>Record payment</button><button className="danger-link" onClick={onCancel}>Cancel Deal</button></>}<button className="secondary-button" onClick={onClose}>Back to Deals</button></div><div><h3>Transport</h3>{!cancelled && <button className="primary-button" onClick={onTrip}>+ Add truck</button>}{trips.length ? trips.map((trip) => <article className="record-card" key={trip.id}><strong>{trip.truckNumber}</strong><p>Assigned {formatDate(trip.assignedDate)}</p><span>Freight {currency.format(trip.freight)}</span></article>) : <div className="empty-callout">No truck assigned yet.</div>}</div></div></div> }
function PartyProfile({ party, deals, outstanding, onClose, onOpenDeal, onDelete }: { party: Party; deals: Deal[]; outstanding: (deal: Deal) => number; onClose: () => void; onOpenDeal: (id: string) => void; onDelete: () => void }) { const liveDeals = deals.filter((deal) => deal.stage !== 'Cancelled'); const totalValue = liveDeals.reduce((sum, deal) => sum + dealValue(deal), 0); const totalDue = liveDeals.reduce((sum, deal) => sum + outstanding(deal), 0); const commodities = [...new Set(deals.map((deal) => deal.commodity))].join(', ') || 'None yet'; return <div><div className="ledger-cards"><article className="summary-card"><div><p>Business value</p><strong>{currency.format(totalValue)}</strong></div></article><article className="summary-card"><div><p>Outstanding</p><strong>{currency.format(totalDue)}</strong></div></article><article className="summary-card"><div><p>Commodities</p><strong>{commodities}</strong></div></article></div><div className="two-table"><div><h3>{party.name}</h3><article className="record-card"><strong>{party.phone || 'No phone saved'}</strong><p>{party.location || 'No location saved'}</p><span>Trust: {party.trust}</span><p>{party.notes || 'No business notes yet.'}</p></article><button className="secondary-button" onClick={onClose}>Back to Parties</button><button className="danger-link" onClick={onDelete}>Delete Party</button></div><div><h3>Deal history</h3>{deals.length ? deals.map((deal) => <article className="record-card" key={deal.id}><strong>Daily {deal.dailySerial} · {deal.commodity}</strong><p>{formatDate(deal.dealDate)} · {deal.stage}</p><span>{currency.format(dealValue(deal))} · Due {currency.format(outstanding(deal))}</span><button className="text-button" onClick={() => onOpenDeal(deal.id)}>Open Deal →</button></article>) : <div className="empty-callout">No business history yet.</div>}</div></div></div> }
