import { useState } from 'react'
import type { FormEvent } from 'react'
import './App.css'
import { currency, dealValue, monthlyKey, partyName, stages, today } from './domain'
import type { Deal, DealStage, LedgerType, Party } from './domain'
import { resetLocalData, useAppData } from './storage'

type Page = 'Dashboard' | 'Deals' | 'Parties' | 'Offers & Requirements' | 'Transport' | 'Payments' | 'Daily Register' | 'Monthly Ledger' | 'To-Do'
type ModalType = 'deal' | 'party' | 'payment' | 'trip' | 'offer' | 'requirement' | 'commission' | 'transporter' | 'truck' | 'todo' | null
const nav: Page[] = ['Dashboard', 'Deals', 'Parties', 'Offers & Requirements', 'Transport', 'Payments', 'Daily Register', 'Monthly Ledger', 'To-Do']
const uid = (kind: string) => `${kind}-${crypto.randomUUID()}`

export default function App() {
  const [data, setData] = useAppData()
  const [page, setPage] = useState<Page>('Dashboard')
  const [modal, setModal] = useState<ModalType>(null)
  const [returnToDeal, setReturnToDeal] = useState(false)
  const [selectedDealId, setSelectedDealId] = useState<string | null>(null)
  const [selectedPartyId, setSelectedPartyId] = useState<string | null>(null)
  const [notice, setNotice] = useState('')
  const selectedDeal = data.deals.find((deal) => deal.id === selectedDealId)
  const selectedParty = data.parties.find((party) => party.id === selectedPartyId)
  const name = (id: string) => partyName(data.parties, id)
  const paymentTotal = (id: string, ledger: LedgerType) => data.payments.filter((p) => p.dealId === id && p.ledger === ledger).reduce((sum, p) => sum + p.amount, 0)
  const obligation = (deal: Deal, ledger: LedgerType) => ledger === 'Commodity' ? { amount: dealValue(deal), expectedPayment: deal.expectedPayment } : data.obligations.find((item) => item.dealId === deal.id && item.ledger === ledger)
  const dueFor = (deal: Deal, ledger: LedgerType) => Math.max(0, (obligation(deal, ledger)?.amount ?? 0) - paymentTotal(deal.id, ledger))
  const due = (deal: Deal) => dueFor(deal, 'Commodity')
  const active = data.deals.filter((deal) => !['Closed', 'Cancelled'].includes(deal.stage))
  const overdue = data.deals.filter((deal) => deal.stage !== 'Cancelled' && due(deal) > 0 && deal.expectedPayment < today)
  const updateDeal = (id: string, changes: Partial<Deal>) => {
    const deal = data.deals.find((item) => item.id === id)
    if (!deal || deal.stage === 'Cancelled') { setNotice('Cancelled Deals keep their history and cannot be changed.'); return }
    setData({ ...data, deals: data.deals.map((item) => item.id === id ? { ...item, ...changes } : item) })
  }
  const cancelDeal = (id: string) => {
    const deal = data.deals.find((item) => item.id === id)
    if (!deal || deal.stage === 'Cancelled') return
    const reason = window.prompt('Cancellation reason (required):')?.trim()
    if (!reason) { setNotice('Cancellation was not saved because a reason is required.'); return }
    updateDeal(id, { stage: 'Cancelled', cancelledReason: reason })
    setNotice(`Deal ${deal.dailySerial} was cancelled. Its trips and payments remain in history, but it is excluded from totals.`)
  }

  const createParty = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = new FormData(event.currentTarget)
    const party: Party = { id: uid('party'), name: String(form.get('name')).trim(), phone: String(form.get('phone')), location: String(form.get('location')), trust: 'Normal', notes: String(form.get('notes')) }
    setData({ ...data, parties: [...data.parties, party] }); setNotice(`${party.name} was added. Choose it as buyer or seller on any Deal.`); setModal(returnToDeal ? 'deal' : null); setReturnToDeal(false)
  }
  const createDeal = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = new FormData(event.currentTarget); const date = String(form.get('dealDate'))
    const daily = data.deals.filter((deal) => deal.dealDate === date); const monthly = data.deals.filter((deal) => monthlyKey(deal.dealDate) === monthlyKey(date))
    const deal: Deal = { id: uid('deal'), dealDate: date, dailySerial: Math.max(0, ...daily.map((d) => d.dailySerial)) + 1, monthlySerial: Math.max(0, ...monthly.map((d) => d.monthlySerial)) + 1, buyerId: String(form.get('buyer')), sellerId: String(form.get('seller')), commodity: String(form.get('commodity')), quantity: Number(form.get('quantity')), rate: Number(form.get('rate')), route: String(form.get('route')), expectedPayment: String(form.get('expectedPayment')), stage: 'Matching', truck: '' }
    setData({ ...data, deals: [...data.deals, deal] }); setSelectedDealId(deal.id); setModal(null); setNotice(`Deal ${deal.dailySerial} created. Open it to add trucks, payments, or move its status.`)
  }
  const addTrip = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); if (!selectedDeal || selectedDeal.stage === 'Cancelled') { setModal(null); setNotice('A cancelled Deal cannot receive a new truck.'); return }; const form = new FormData(event.currentTarget); const truck = String(form.get('truck'))
    setData({ ...data, dealTrips: [...data.dealTrips, { id: uid('trip'), dealId: selectedDeal.id, transporterId: String(form.get('transporter')), truckNumber: truck, freight: Number(form.get('freight')), assignedDate: String(form.get('assignedDate')), notes: String(form.get('notes')) }], deals: data.deals.map((d) => d.id === selectedDeal.id && d.stage === 'Matching' ? { ...d, truck, stage: 'Truck Assigned' } : d) }); setModal(null); setNotice('Truck added to this Deal.');
  }
  const createPayment = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); const dealId = String(f.get('deal')); const ledger = String(f.get('ledger')) as LedgerType; const deal = data.deals.find((item) => item.id === dealId); if (!deal || deal.stage === 'Cancelled') { setModal(null); setNotice('A cancelled Deal retains prior payments but cannot receive a new one.'); return }; if (!obligation(deal, ledger)) { setNotice(`Set the ${ledger.toLowerCase()} obligation before recording its payment.`); return }; setData({ ...data, payments: [...data.payments, { id: uid('payment'), dealId, ledger, amount: Number(f.get('amount')), date: String(f.get('date')), note: String(f.get('note')) }] }); setModal(null); setNotice(`${ledger} payment recorded; balance recalculated.`) }
  const saveCommission = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selectedDeal || selectedDeal.stage === 'Cancelled') return; const form = new FormData(event.currentTarget); const ledger = String(form.get('ledger')) as LedgerType; const next = { id: uid('obligation'), dealId: selectedDeal.id, ledger, amount: Number(form.get('amount')), expectedPayment: String(form.get('expectedPayment')) }; setData({ ...data, obligations: [...data.obligations.filter((item) => !(item.dealId === selectedDeal.id && item.ledger === ledger)), next] }); setModal(null); setNotice(`${ledger} obligation saved.`) }
  const createTransporter = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const transporter = { id: uid('transporter'), name: String(form.get('name')).trim(), phone: String(form.get('phone')), routes: String(form.get('routes')), reliability: String(form.get('reliability')) as 'High' | 'Normal' | 'Watch' }; setData({ ...data, transporters: [...data.transporters, transporter] }); setModal(null); setNotice(`${transporter.name} added to Transport.`) }
  const createTruck = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const number = String(form.get('number')).trim().toUpperCase(); if (data.trucks.some((truck) => truck.number === number)) { setNotice('This truck number already exists.'); return }; setData({ ...data, trucks: [...data.trucks, { id: uid('truck'), number, transporterId: String(form.get('transporter')), capacity: String(form.get('capacity')), driverPhone: String(form.get('driverPhone')) }] }); setModal(null); setNotice(`${number} added to Transport.`) }
  const createTodo = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const text = String(form.get('text')).trim(); if (!text) return; setData({ ...data, todos: [...data.todos, { id: uid('todo'), text, done: false, due: String(form.get('due')) }] }); setModal(null); setNotice('Follow-up added.') }
  const exportRegister = (records: Deal[], filename: string) => { const headers = ['Date', 'Daily No.', 'Monthly No.', 'Buyer', 'Seller', 'Commodity', 'Quantity Qtl', 'Rate', 'Value', 'Route', 'Stage', 'Commodity Due', 'Buyer Commission Due', 'Seller Commission Due']; const rows = records.map((deal) => [deal.dealDate, deal.dailySerial, deal.monthlySerial, name(deal.buyerId), name(deal.sellerId), deal.commodity, deal.quantity, deal.rate, dealValue(deal), deal.route, deal.stage, deal.stage === 'Cancelled' ? 'Excluded' : dueFor(deal, 'Commodity'), deal.stage === 'Cancelled' ? 'Excluded' : dueFor(deal, 'Buyer Commission'), deal.stage === 'Cancelled' ? 'Excluded' : dueFor(deal, 'Seller Commission')]); const csv = [headers, ...rows].map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); link.download = filename; link.click(); URL.revokeObjectURL(link.href); setNotice('Excel-compatible register exported.') }
  const createMarketRecord = (event: FormEvent<HTMLFormElement>, kind: 'offer' | 'requirement') => { event.preventDefault(); const form = new FormData(event.currentTarget); if (kind === 'offer') setData({ ...data, offers: [...data.offers, { id: uid('offer'), sellerId: String(form.get('party')), commodity: String(form.get('commodity')), quantity: Number(form.get('quantity')), rate: Number(form.get('rate')), location: String(form.get('location')), status: 'Open' }] }); else setData({ ...data, requirements: [...data.requirements, { id: uid('requirement'), buyerId: String(form.get('party')), commodity: String(form.get('commodity')), quantity: Number(form.get('quantity')), targetRate: Number(form.get('rate')), deliveryLocation: String(form.get('location')), status: 'Open' }] }); setModal(null); setNotice(`${kind === 'offer' ? 'Seller offer' : 'Buyer requirement'} saved. It remains separate until you create a Deal.`) }
  const openDeal = (id: string) => { setSelectedDealId(id); setPage('Deals') }

  const dealRows = (records: Deal[]) => <div className="table-wrap"><table><thead><tr><th>Deal</th><th>Buyer / Seller</th><th>Commodity</th><th>Status</th><th>Outstanding</th><th/></tr></thead><tbody>{records.map((deal) => <tr key={deal.id}><td><strong>Daily {deal.dailySerial}</strong><small>{deal.dealDate} · M{deal.monthlySerial}</small></td><td><strong>{name(deal.buyerId)}</strong><small>{name(deal.sellerId)}</small></td><td>{deal.commodity}<small>{deal.quantity} Qtl · {currency.format(deal.rate)}/Qtl</small></td><td><span className={`status status-${deal.stage.toLowerCase().replace(' ', '-')}`}>{deal.stage}</span></td><td>{deal.stage === 'Cancelled' ? 'Excluded' : currency.format(due(deal))}</td><td><button className="text-button" onClick={() => openDeal(deal.id)}>Open →</button></td></tr>)}</tbody></table></div>
  const dashboard = <><section className="panel page-panel"><div className="panel-heading"><div><p className="eyebrow">WORKING NOW</p><h2>Active Deals</h2><p className="section-subtitle">Open a Deal to add its truck, record payments, and advance its status.</p></div><button className="primary-button" onClick={() => setModal('deal')}>+ New Deal</button></div>{dealRows(active)}</section><section className="bottom-grid"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">TODAY</p><h2>To-Do</h2></div><button className="text-button" onClick={() => setPage('To-Do')}>Open →</button></div><div className="todo-list">{data.todos.filter((todo) => !todo.done).slice(0, 5).map((todo) => <label key={todo.id}><input type="checkbox" checked={todo.done} onChange={() => setData({ ...data, todos: data.todos.map((item) => item.id === todo.id ? { ...item, done: !item.done } : item) })}/><span>{todo.text}</span><small>{todo.due}</small></label>)}</div></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">ATTENTION</p><h2>Overdue Payments</h2></div><button className="text-button" onClick={() => setPage('Payments')}>Open →</button></div>{overdue.length ? overdue.map((deal) => <div className="attention-row" key={deal.id}><div><strong>Deal {deal.dailySerial} · {name(deal.buyerId)}</strong><p>{currency.format(due(deal))} overdue since {deal.expectedPayment}</p></div></div>) : <div className="empty-callout">No overdue payments.</div>}</section></section></>
  let content: React.ReactNode = dashboard
  if (page === 'Deals') content = <Section title="Deals" subtitle="Create the deal once; manage all later action from its Deal record." action="+ New Deal" onAction={() => setModal('deal')}>{selectedDeal ? <DealWorkspace deal={selectedDeal} trips={data.dealTrips.filter((trip) => trip.dealId === selectedDeal.id)} name={name} due={due(selectedDeal)} buyerCommission={dueFor(selectedDeal, 'Buyer Commission')} sellerCommission={dueFor(selectedDeal, 'Seller Commission')} onClose={() => setSelectedDealId(null)} onStage={(stage) => updateDeal(selectedDeal.id, { stage })} onTrip={() => setModal('trip')} onPayment={() => setModal('payment')} onCommission={() => setModal('commission')} onCancel={() => cancelDeal(selectedDeal.id)} /> : dealRows(data.deals)}</Section>
  if (page === 'Parties') content = <Section title="Parties" subtitle="Party details are stored once. Buyer and seller are Deal roles, not party types." action="+ Add Party" onAction={() => setModal('party')}>{selectedParty ? <PartyProfile party={selectedParty} deals={data.deals.filter((deal) => deal.buyerId === selectedParty.id || deal.sellerId === selectedParty.id)} outstanding={(deal) => due(deal)} onClose={() => setSelectedPartyId(null)} onOpenDeal={openDeal} /> : <div className="table-wrap"><table><thead><tr><th>Party</th><th>Phone</th><th>Location</th><th>Trust</th><th>Deals</th><th/></tr></thead><tbody>{data.parties.map((party) => <tr key={party.id}><td><strong>{party.name}</strong><small>{party.notes || 'No notes'}</small></td><td>{party.phone || '—'}</td><td>{party.location || '—'}</td><td>{party.trust}</td><td>{data.deals.filter((d) => d.buyerId === party.id || d.sellerId === party.id).length}</td><td><button className="text-button" onClick={() => setSelectedPartyId(party.id)}>Open →</button></td></tr>)}</tbody></table></div>}</Section>
  if (page === 'Offers & Requirements') { const matches = data.offers.filter((offer) => offer.status === 'Open').flatMap((offer) => data.requirements.filter((requirement) => requirement.status === 'Open' && requirement.commodity === offer.commodity).map((requirement) => ({ offer, requirement }))); content = <Section title="Offers & Requirements" subtitle="Keep availability and demand separate until you explicitly create a Deal."><div className="split-actions"><button className="primary-button" onClick={() => setModal('offer')}>+ Seller Offer</button><button className="secondary-button" onClick={() => setModal('requirement')}>+ Buyer Requirement</button></div><div className="two-table"><div><h3>Seller offers</h3>{data.offers.filter((offer) => offer.status === 'Open').map((offer) => <article className="record-card" key={offer.id}><strong>{offer.commodity} · {offer.quantity} Qtl</strong><p>{name(offer.sellerId)} · {offer.location}</p><span>{currency.format(offer.rate)}/Qtl</span></article>)}</div><div><h3>Buyer requirements</h3>{data.requirements.filter((requirement) => requirement.status === 'Open').map((requirement) => <article className="record-card" key={requirement.id}><strong>{requirement.commodity} · {requirement.quantity} Qtl</strong><p>{name(requirement.buyerId)} · {requirement.deliveryLocation}</p><span>Target {currency.format(requirement.targetRate)}/Qtl</span></article>)}</div></div><div className="match-note">{matches.length ? `${matches.length} possible match${matches.length === 1 ? '' : 'es'} found by commodity. Review the parties, rate and quantity, then create a Deal manually.` : 'No open commodity matches currently.'} <button className="text-button" onClick={() => setModal('deal')}>Create Deal manually →</button></div></Section> }
  if (page === 'Transport') { const freightTrips = data.dealTrips.filter((trip) => data.deals.find((deal) => deal.id === trip.dealId)?.stage !== 'Cancelled'); content = <Section title="Transport" subtitle="Transport is added to the Deal; this screen keeps transporter, truck and freight memory easy to find."><div className="split-actions"><button className="primary-button" onClick={() => setModal('transporter')}>+ Add Transporter</button><button className="secondary-button" onClick={() => setModal('truck')}>+ Add Truck</button></div><div className="two-table"><div><h3>Transporters</h3>{data.transporters.map((t) => <article className="record-card" key={t.id}><strong>{t.name}</strong><p>{t.routes || 'Routes not entered'}</p><span>{t.phone || 'No phone'} · {t.reliability} reliability</span></article>)}</div><div><h3>Known trucks</h3>{data.trucks.map((t) => <article className="record-card" key={t.id}><strong>{t.number}</strong><p>{data.transporters.find((x) => x.id === t.transporterId)?.name ?? 'Unknown transporter'}</p><span>{t.capacity || 'Capacity not entered'} · Driver phone: {t.driverPhone || 'Not entered'}</span></article>)}</div></div><div className="two-table"><div><h3>Freight history</h3>{freightTrips.length ? freightTrips.map((trip) => { const deal = data.deals.find((item) => item.id === trip.dealId); const transporter = data.transporters.find((item) => item.id === trip.transporterId); return <article className="record-card" key={trip.id}><strong>{transporter?.name ?? 'Unknown transporter'} · {deal?.route ?? 'Route not entered'}</strong><p>{trip.truckNumber} · Deal {deal?.dailySerial ?? '—'} · {trip.assignedDate}</p><span>Freight {currency.format(trip.freight)}</span></article> }) : <div className="empty-callout">Freight history appears after a truck is assigned to a Deal.</div>}</div></div></Section> }
  if (page === 'Payments') content = <Section title="Payments & Commissions" subtitle="Commodity, buyer commission and seller commission are separate ledgers." action="+ Record Payment" onAction={() => setModal('payment')}><div className="ledger-cards"><Metric title="Commodity outstanding" value={currency.format(data.deals.filter((deal) => deal.stage !== 'Cancelled').reduce((sum, deal) => sum + dueFor(deal, 'Commodity'), 0))}/><Metric title="Buyer commission due" value={currency.format(data.deals.filter((deal) => deal.stage !== 'Cancelled').reduce((sum, deal) => sum + dueFor(deal, 'Buyer Commission'), 0))}/><Metric title="Seller commission due" value={currency.format(data.deals.filter((deal) => deal.stage !== 'Cancelled').reduce((sum, deal) => sum + dueFor(deal, 'Seller Commission'), 0))}/></div>{dealRows(data.deals)}</Section>
  if (page === 'Daily Register') { const records = data.deals.filter((d) => d.dealDate === today); content = <Section title="Daily Register" subtitle="Derived directly from the business records for the selected business day." action="Export Excel" onAction={() => exportRegister(records, `daily-register-${today}.csv`)}>{dealRows(records)}</Section> }
  if (page === 'Monthly Ledger') { const records = data.deals.filter((deal) => monthlyKey(deal.dealDate) === monthlyKey(today)); const included = records.filter((deal) => deal.stage !== 'Cancelled'); content = <Section title="Monthly Ledger" subtitle="Derived from underlying records. Cancelled Deals remain visible but are excluded from totals." action="Print / Save PDF" onAction={() => window.print()}><div className="ledger-cards"><Metric title="Business value" value={currency.format(included.reduce((sum, deal) => sum + dealValue(deal), 0))}/><Metric title="Commodity due" value={currency.format(included.reduce((sum, deal) => sum + dueFor(deal, 'Commodity'), 0))}/><Metric title="Commission due" value={currency.format(included.reduce((sum, deal) => sum + dueFor(deal, 'Buyer Commission') + dueFor(deal, 'Seller Commission'), 0))}/></div>{dealRows(records)}</Section> }
  if (page === 'To-Do') content = <Section title="To-Do" subtitle="Simple follow-ups for the broker’s day." action="+ Add Follow-up" onAction={() => setModal('todo')}><div className="todo-list">{data.todos.map((todo) => <label key={todo.id}><input type="checkbox" checked={todo.done} onChange={() => setData({ ...data, todos: data.todos.map((x) => x.id === todo.id ? { ...x, done: !x.done } : x) })}/><span>{todo.text}</span><small>{todo.due}</small></label>)}</div></Section>

  const modalTitle = modal === 'deal' ? 'New Deal' : modal === 'party' ? 'New Party' : modal === 'trip' ? 'Add Truck to Deal' : modal === 'offer' ? 'Record Seller Offer' : modal === 'requirement' ? 'Record Buyer Requirement' : modal === 'commission' ? 'Set Commission Obligation' : modal === 'transporter' ? 'Add Transporter' : modal === 'truck' ? 'Add Truck' : modal === 'todo' ? 'Add Follow-up' : 'Record Payment'
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">SB</span><span>Shree Balaje<small>Broker</small></span></div><nav>{nav.map((item) => <button key={item} className={page === item ? 'nav-item active' : 'nav-item'} onClick={() => { setPage(item); if (item !== 'Deals') setSelectedDealId(null) }}><span>◇</span>{item}</button>)}</nav><div className="sidebar-footer">Local workspace<br/><small>Cloud connection ready</small></div></aside><main><header className="topbar"><div><p className="eyebrow">Saturday, 06 September 2026</p><h1>{page === 'Dashboard' ? "Today's Business" : page}</h1></div><div className="header-actions"><button className="secondary-button" onClick={() => { if (window.confirm('Reset local demo records?')) { resetLocalData(); window.location.reload() } }}>Reset demo</button><button className="primary-button" onClick={() => setModal('deal')}>+ New Deal</button></div></header>{notice && <div className="toast">{notice}<button onClick={() => setNotice('')}>×</button></div>}{content}</main>{modal && <Modal title={modalTitle} onClose={() => setModal(null)}>{modal === 'deal' && <DealForm parties={data.parties} onSubmit={createDeal} onAddParty={() => { setReturnToDeal(true); setModal('party') }}/>} {modal === 'party' && <PartyForm onSubmit={createParty}/>} {modal === 'trip' && <TripForm transporters={data.transporters} trucks={data.trucks} onSubmit={addTrip}/>} {modal === 'payment' && <PaymentForm deals={data.deals} selectedDealId={selectedDealId} onSubmit={createPayment}/>} {modal === 'commission' && <CommissionForm onSubmit={saveCommission}/>} {modal === 'transporter' && <TransporterForm onSubmit={createTransporter}/>} {modal === 'truck' && <TruckForm transporters={data.transporters} onSubmit={createTruck}/>} {modal === 'todo' && <TodoForm onSubmit={createTodo}/>} {(modal === 'offer' || modal === 'requirement') && <MarketForm kind={modal} parties={data.parties} onSubmit={(event) => createMarketRecord(event, modal)}/>}</Modal>}</div>
}

function Section({ title, subtitle, action, onAction, children }: { title: string; subtitle: string; action?: string; onAction?: () => void; children: React.ReactNode }) { return <section className="panel page-panel"><div className="panel-heading"><div><p className="eyebrow">BUSINESS WORKSPACE</p><h2>{title}</h2><p className="section-subtitle">{subtitle}</p></div>{action && <button className="primary-button" onClick={onAction}>{action}</button>}</div>{children}</section> }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="modal-backdrop"><section className="deal-modal" role="dialog" aria-modal="true"><div className="modal-heading"><div><p className="eyebrow">DEAL WORKSPACE</p><h2>{title}</h2></div><button className="close-button" onClick={onClose}>×</button></div>{children}</section></div> }
function DealForm({ parties, onSubmit, onAddParty }: { parties: Party[]; onSubmit: (e: FormEvent<HTMLFormElement>) => void; onAddParty: () => void }) { return <form onSubmit={onSubmit}><div className="form-grid"><label>Deal date<input name="dealDate" type="date" defaultValue={today} required/></label><label>Buyer <select name="buyer" required>{parties.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Seller <select name="seller" required>{parties.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button type="button" className="secondary-button" onClick={onAddParty}>+ Add new party</button><label>Commodity<select name="commodity"><option>Paddy</option><option>Wheat</option><option>Rice</option></select></label><label>Quantity (Qtl)<input name="quantity" type="number" min="0.01" step="0.01" required/></label><label>Rate (₹/Qtl)<input name="rate" type="number" min="0" required/></label><label>Route<input name="route" required/></label><label>Expected payment<input name="expectedPayment" type="date" required/></label></div><div className="form-note">This captures the deal once. Add transport, payment and stage updates from the Deal afterwards.</div><div className="form-actions"><button className="primary-button">Create Deal</button></div></form> }
function PartyForm({ onSubmit }: { onSubmit: (e: FormEvent<HTMLFormElement>) => void }) { return <form onSubmit={onSubmit}><div className="form-grid"><label>Party name<input name="name" required/></label><label>Phone<input name="phone"/></label><label>Location<input name="location"/></label><label className="span-two">Notes<textarea name="notes"/></label></div><div className="form-actions"><button className="primary-button">Save Party</button></div></form> }
function MarketForm({ kind, parties, onSubmit }: { kind: 'offer' | 'requirement'; parties: Party[]; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form onSubmit={onSubmit}><div className="form-grid"><label>{kind === 'offer' ? 'Seller' : 'Buyer'}<select name="party">{parties.map((party) => <option key={party.id} value={party.id}>{party.name}</option>)}</select></label><label>Commodity<select name="commodity"><option>Paddy</option><option>Wheat</option><option>Rice</option></select></label><label>Quantity (Qtl)<input name="quantity" type="number" min="0.01" step="0.01" required/></label><label>{kind === 'offer' ? 'Rate' : 'Target rate'} (₹/Qtl)<input name="rate" type="number" min="0" required/></label><label className="span-two">{kind === 'offer' ? 'Location' : 'Delivery location'}<input name="location" required/></label></div><div className="form-note">This remains separate until you explicitly create a Deal.</div><div className="form-actions"><button className="primary-button">Save {kind === 'offer' ? 'Offer' : 'Requirement'}</button></div></form> }
function TripForm({ transporters, trucks, onSubmit }: { transporters: { id: string; name: string }[]; trucks: { number: string; transporterId: string }[]; onSubmit: (e: FormEvent<HTMLFormElement>) => void }) { return <form onSubmit={onSubmit}><div className="form-grid"><label>Transporter<select name="transporter">{transporters.map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Truck<select name="truck">{trucks.map((t) => <option key={t.number} value={t.number}>{t.number}</option>)}</select></label><label>Freight (₹)<input name="freight" type="number" min="0" required/></label><label>Assigned date<input name="assignedDate" type="date" defaultValue={today} required/></label><label className="span-two">Notes<textarea name="notes"/></label></div><div className="form-actions"><button className="primary-button">Add Truck</button></div></form> }
function Metric({ title, value }: { title: string; value: string }) { return <article className="summary-card"><div><p>{title}</p><strong>{value}</strong></div></article> }
function PaymentForm({ deals, selectedDealId, onSubmit }: { deals: Deal[]; selectedDealId: string | null; onSubmit: (e: FormEvent<HTMLFormElement>) => void }) { return <form onSubmit={onSubmit}><div className="form-grid"><label>Deal<select name="deal" defaultValue={selectedDealId ?? undefined}>{deals.filter((deal) => deal.stage !== 'Cancelled').map((d) => <option key={d.id} value={d.id}>Daily {d.dailySerial}</option>)}</select></label><label>Ledger<select name="ledger"><option>Commodity</option><option>Buyer Commission</option><option>Seller Commission</option></select></label><label>Amount (₹)<input name="amount" type="number" min="1" required/></label><label>Date<input name="date" type="date" defaultValue={today} required/></label><label className="span-two">Note<textarea name="note"/></label></div><div className="form-note">Partial entries are unlimited. Each ledger balance is calculated from its obligation and payment history.</div><div className="form-actions"><button className="primary-button">Save Payment</button></div></form> }
function CommissionForm({ onSubmit }: { onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form onSubmit={onSubmit}><div className="form-grid"><label>Commission due from<select name="ledger"><option>Buyer Commission</option><option>Seller Commission</option></select></label><label>Amount (₹)<input name="amount" type="number" min="0" required/></label><label>Expected payment<input name="expectedPayment" type="date" defaultValue={today} required/></label></div><div className="form-note">Commission is intentionally separate from the commodity settlement.</div><div className="form-actions"><button className="primary-button">Save Commission</button></div></form> }
function TransporterForm({ onSubmit }: { onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form onSubmit={onSubmit}><div className="form-grid"><label>Transporter name<input name="name" required/></label><label>Phone<input name="phone"/></label><label>Routes<input name="routes" placeholder="e.g. Buxar – Patna"/></label><label>Reliability<select name="reliability"><option>Normal</option><option>High</option><option>Watch</option></select></label></div><div className="form-actions"><button className="primary-button">Save Transporter</button></div></form> }
function TruckForm({ transporters, onSubmit }: { transporters: { id: string; name: string }[]; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form onSubmit={onSubmit}><div className="form-grid"><label>Truck number<input name="number" placeholder="BR 01 GK 4821" required/></label><label>Transporter<select name="transporter">{transporters.map((transporter) => <option key={transporter.id} value={transporter.id}>{transporter.name}</option>)}</select></label><label>Capacity (Qtl)<input name="capacity" type="number" min="0"/></label><label>Driver phone (optional)<input name="driverPhone" type="tel"/></label></div><div className="form-note">Driver name is intentionally not stored.</div><div className="form-actions"><button className="primary-button">Save Truck</button></div></form> }
function TodoForm({ onSubmit }: { onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <form onSubmit={onSubmit}><div className="form-grid"><label className="span-two">Follow-up<input name="text" placeholder="e.g. Confirm unloading" required/></label><label>Due date<input name="due" type="date" defaultValue={today} required/></label></div><div className="form-actions"><button className="primary-button">Save Follow-up</button></div></form> }
function DealWorkspace({ deal, trips, name, due, buyerCommission, sellerCommission, onClose, onStage, onTrip, onPayment, onCommission, onCancel }: { deal: Deal; trips: { id: string; truckNumber: string; freight: number; assignedDate: string }[]; name: (id: string) => string; due: number; buyerCommission: number; sellerCommission: number; onClose: () => void; onStage: (stage: DealStage) => void; onTrip: () => void; onPayment: () => void; onCommission: () => void; onCancel: () => void }) { const cancelled = deal.stage === 'Cancelled'; return <div><div className="ledger-cards"><Metric title="Commodity due" value={currency.format(due)}/><Metric title="Buyer commission due" value={currency.format(buyerCommission)}/><Metric title="Seller commission due" value={currency.format(sellerCommission)}/></div><div className="two-table"><div><h3>Deal {deal.dailySerial}</h3><article className="record-card"><strong>{name(deal.buyerId)} ← {name(deal.sellerId)}</strong><p>{deal.commodity} · {deal.quantity} Qtl · {currency.format(dealValue(deal))}</p><span>{cancelled ? `Cancelled: ${deal.cancelledReason}` : `Commodity due: ${currency.format(due)}`}</span></article>{cancelled ? <div className="empty-callout">Cancelled Deals are retained as history. Their existing payments and trips remain visible, but new changes are blocked.</div> : <><label>Stage<select value={deal.stage} onChange={(e) => onStage(e.target.value as DealStage)}>{stages.map((stage) => <option key={stage}>{stage}</option>)}</select></label><button className="secondary-button" onClick={onCommission}>Set commission</button><button className="secondary-button" onClick={onPayment}>Record payment</button><button className="danger-link" onClick={onCancel}>Cancel Deal</button></>}<button className="secondary-button" onClick={onClose}>Back to Deals</button></div><div><h3>Transport</h3>{!cancelled && <button className="primary-button" onClick={onTrip}>+ Add truck</button>}{trips.length ? trips.map((trip) => <article className="record-card" key={trip.id}><strong>{trip.truckNumber}</strong><p>Assigned {trip.assignedDate}</p><span>Freight {currency.format(trip.freight)}</span></article>) : <div className="empty-callout">No truck assigned yet.</div>}</div></div></div> }
function PartyProfile({ party, deals, outstanding, onClose, onOpenDeal }: { party: Party; deals: Deal[]; outstanding: (deal: Deal) => number; onClose: () => void; onOpenDeal: (id: string) => void }) { const liveDeals = deals.filter((deal) => deal.stage !== 'Cancelled'); const totalValue = liveDeals.reduce((sum, deal) => sum + dealValue(deal), 0); const totalDue = liveDeals.reduce((sum, deal) => sum + outstanding(deal), 0); const commodities = [...new Set(deals.map((deal) => deal.commodity))].join(', ') || 'None yet'; return <div><div className="ledger-cards"><article className="summary-card"><div><p>Business value</p><strong>{currency.format(totalValue)}</strong></div></article><article className="summary-card"><div><p>Outstanding</p><strong>{currency.format(totalDue)}</strong></div></article><article className="summary-card"><div><p>Commodities</p><strong>{commodities}</strong></div></article></div><div className="two-table"><div><h3>{party.name}</h3><article className="record-card"><strong>{party.phone || 'No phone saved'}</strong><p>{party.location || 'No location saved'}</p><span>Trust: {party.trust}</span><p>{party.notes || 'No business notes yet.'}</p></article><button className="secondary-button" onClick={onClose}>Back to Parties</button></div><div><h3>Deal history</h3>{deals.length ? deals.map((deal) => <article className="record-card" key={deal.id}><strong>Daily {deal.dailySerial} · {deal.commodity}</strong><p>{deal.dealDate} · {deal.stage}</p><span>{currency.format(dealValue(deal))} · Due {currency.format(outstanding(deal))}</span><button className="text-button" onClick={() => onOpenDeal(deal.id)}>Open Deal →</button></article>) : <div className="empty-callout">No business history yet.</div>}</div></div></div> }
